function init(self)
	msg.post(".", "acquire_input_focus")
	self.lose_box = gui.get_node("lose_box")
	self.lose_text = gui.get_node("lose_text")
	self.lose_button_box = gui.get_node("lose_button_box")
	self.lose_button_text = gui.get_node("lose_button_text")
end

function on_message(self, message_id, message)

	if message_id == hash("show_lose") then
		gui.set_visible(self.lose_box, true)
		gui.set_visible(self.lose_text, true)
		gui.set_visible(self.lose_button_box, true)
		gui.set_visible(self.lose_button_text, true)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(self.lose_button_box, action.x, action.y) then
			msg.post("main:/go#main", "retry")
		end
	end
end