CELL_SIZE = 64
local levels = require("main.levels")
local dirs = {
	right = {dx = 1, dy = 0},   -- right
	up = {dx = 0, dy = 1},   -- up
	left = {dx = -1, dy = 0},  -- left
	down = {dx = 0, dy = -1},  -- down
}

local function remove_arrow(self, id_to_delete)
	for i, arrow_data in ipairs(self.arrows) do
		if arrow_data.id == id_to_delete then
			table.remove(self.arrows, i)
		end
	end
	
	if #self.arrows == 0 then
		collectionfactory.create("#win_collection")
	end
end

local function check_path(self, message)
	local blocked = false
	local coord = {}

	for _, a in ipairs(self.arrows) do
		-- проверка по линии
		if message.dx == 1 then
			if a.y == message.y and a.x > message.x then
				if not coord[1] or coord[1].x > a.x then
					table.remove(coord, 1)
					table.insert(coord, { x = a.x, y = a.y})
				end
				blocked = true
			end
		elseif message.dx == -1 then
			if a.y == message.y and a.x < message.x then
				if not coord[1] or coord[1].x < a.x then
					table.remove(coord, 1)
					table.insert(coord, { x = a.x, y = a.y})
				end
				blocked = true
			end
		elseif message.dy == 1 then
			if a.x == message.x and a.y > message.y then
				if not coord[1] or coord[1].y > a.y then
					table.remove(coord, 1)
					table.insert(coord, { x = a.x, y = a.y})
				end
				blocked = true
			end
		elseif message.dy == -1 then
			if a.x == message.x and a.y < message.y then
				if not coord[1] or coord[1].y < a.y then
					table.remove(coord, 1)
					table.insert(coord, { x = a.x, y = a.y})
				end
				blocked = true
			end
		end
	end
	if not blocked then
		msg.post(message.from, "free")
	else msg.post(message.from, "hit", coord[1])
		msg.post("/level_gui#main", "delete_one_live")
	end
end

function init(self)
	math.randomseed(os.time())
	msg.post(".", "acquire_input_focus")
	local current_level = levels.data.current_level
	local level = levels.levels[current_level]

	local offset_x = ((level.width - 1) * CELL_SIZE)/2
	local offset_y = ((level.height - 1) * CELL_SIZE)/2

	self.arrows = {}
	local w, h = window.get_size()
	for y = 1, level.height do
		for x = 1, level.width do

			local string_dir = level.grid[y][x]
			local dir = dirs[string_dir]
			
			
			local pos = vmath.vector3(
			(((x - 1) * CELL_SIZE - offset_x) + w/2),
			(((y - 1) * CELL_SIZE - offset_y) + h/2),
			0
		)
		local angle = math.atan2(dir.dy, dir.dx)
		local quat = vmath.quat_rotation_z(angle)

		local id = factory.create("#arrow_factory", pos, quat, { dx = dir.dx, dy = dir.dy })
		
		table.insert(self.arrows, {
			id = id,
			x = pos.x,
			y = pos.y
		})
		end
	end
end

function on_message(self, message_id, message)
	if message_id == hash("check_path") then
		check_path(self, message)
	end


	if message_id == hash("remove_arrow") then
		remove_arrow(self, message.id)
	end

end
function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		
		-- ищем, в какую стрелку кликнули

		for _, arrow in ipairs(self.arrows) do
			if go.exists(arrow.id) then

				local pos = go.get_position(arrow.id)

				local half = CELL_SIZE / 2

				if math.abs(pos.x - action.x) <= half and
				math.abs(pos.y - action.y) <= half then

					msg.post(arrow.id, "move")
					return
				end
			end
		end
	end
end