local levels = require("main.levels")
function init(self)
	msg.post(".", "acquire_input_focus")
	self.level_button = {}
	for i = 1, #levels.levels do
		local level = string.format("level_%d", i)
		table.insert(self.level_button, gui.get_node(level))
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		for i = 1, #levels.levels do
			if gui.pick_node(self.level_button[i], action.x, action.y) then
				levels.data.current_level = i
				msg.post("main:/go#main", "set_level")
			end
		end
	end
end