go.property('dx', 0)
go.property('dy', 0)
function init(self)
	
end

local function move_forward(self)

	local pos = go.get_position()

	local fly = vmath.vector3(
	pos.x + self.dx * 1000,
	pos.y + self.dy * 1000,
	pos.z
)

go.animate(".", "position",
go.PLAYBACK_ONCE_FORWARD,
fly,
go.EASING_LINEAR,
0.5,
0,
function()
	msg.post("level:/level#main", "remove_arrow", {
		x = pos.x,
		y = pos.y,
		id = go.get_id()
	})
	go.delete()

end)
end

local function bounce_back(self, next_pos)
	local pos = go.get_position()
	local bump = vmath.vector3(
	next_pos.x - (CELL_SIZE - 10) * self.dx,
	next_pos.y - (CELL_SIZE - 10) * self.dy,
	0
	)
	go.animate(".", "position",
	go.PLAYBACK_ONCE_FORWARD,
	bump,
	go.EASING_LINEAR,
	0.04,
	0,
	function()
		go.animate(".", "position",
		go.PLAYBACK_ONCE_FORWARD,
		pos,
		go.EASING_LINEAR,
		0.05)
	end)
end

local function try_move(self)
	local pos = go.get_position()

	msg.post("level:/level#main", "check_path", {
		from = go.get_id(),
		x = pos.x,
		y = pos.y,
		dx = self.dx,
		dy = self.dy
	})
end

function on_input(self, action_id, action)

	if action_id == hash("touch") and action.released then

		local pos = go.get_position()
		local half = 32

		if math.abs(pos.x - action.x) < half and
		math.abs(pos.y - action.y) < half then

			msg.post("level:/level#script", "check_path", {
				from = go.get_id(),
				x = pos.x / CELL_SIZE,
				y = pos.y / CELL_SIZE,
				dx = self.dx,
				dy = self.dy
			})
		end
	end
end

function on_message(self, message_id, message)

	if message_id == hash("move") then
		try_move(self)
	end
	
	if message_id == hash("free") then
		move_forward(self)
	elseif message_id == hash("hit") then
		bounce_back(self, { x = message.x, y = message.y })
	end
end